baseURL: "https://marcuswischer.de"
title: MARCUS WISCHER
paginate: 5
theme: hugo-WonderMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableGitInfo: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Marcus Wischer
  description: "Marcus Wischer Homepage Blog"
  keywords: [Blog, Marcus Wischer, Organisationsentwicklung, Systemtheorie]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true


  label:
    text: "Home"


  # profile-mode
params:
  profileMode:
    enabled: true
    title: " "
    subtitle: '
Wenn eine Blume nicht blüht, reparierst du die Umgebung, in der sie wächst. 


Nicht die Blume.
              '
    imageUrl: /images/avatar.jpg
    imageTitle: "Marcus_Wischer"
    imageWidth: 432
    imageHeight: auto
    buttons:
        - name: Archive
          url: archives

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/marcuswischer/"
    - name: instagram
      url: "https://instagram.com/marcuswischer"
    - name: email
      url: "mailto:hello@marcuswischer.de"
    - name: rss
      url: /index.xml


  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page



  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
#    - identifier: Artikel
#      name: Artikel
#      url: /posts/artikel
#      weight: 10
#    - identifier: Literatur
#      name: Literatur
#      url: /posts/literatur
#      weight: 20
    - identifier: about
      name: Vita & Projekte
      url: /about
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: Suche
      name: Suche
      url: search/
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
