{\rtf1\ansi\ansicpg1252\cocoartf2759
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red49\green49\blue49;\red234\green234\blue234;}
{\*\expandedcolortbl;;\cssrgb\c25098\c25098\c25098;\cssrgb\c93333\c93333\c93333;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
[build]\
publish = "public"  \
command = "hugo --gc --minify" \
\
[context.production.environment]\
HUGO_VERSION = "0.121.2"\
HUGO_ENV = "production"\
HUGO_ENABLEGITINFO = "true"}